"""Pydantic models and payment-domain errors."""

from backend.payments.hsp import HSPConfig, HSPConfigError, HSPReceiptSummary
from backend.payments.service import (
    AP2HotelBookingMandateRequest,
    AP2MandateResponse,
    AP2MandateSummary,
    AP2SignedMandate,
    AP2UserConfirmation,
    AuditEvent,
    BookingContext,
    BookingError,
    BookingMandate,
    ConstraintViolation,
    HotelBookingReceipt,
    HotelBookingRequest,
    HotelBookingResponse,
    PaymentAdapterError,
    PaymentInstructions,
    PaymentProof,
    PaymentReceipt,
    PaymentSimulationError,
    X402RealPaymentError,
)

__all__ = [
    "AP2HotelBookingMandateRequest",
    "AP2MandateResponse",
    "AP2MandateSummary",
    "AP2SignedMandate",
    "AP2UserConfirmation",
    "AuditEvent",
    "BookingContext",
    "BookingError",
    "BookingMandate",
    "ConstraintViolation",
    "HotelBookingReceipt",
    "HotelBookingRequest",
    "HotelBookingResponse",
    "HSPConfig",
    "HSPConfigError",
    "HSPReceiptSummary",
    "PaymentAdapterError",
    "PaymentInstructions",
    "PaymentProof",
    "PaymentReceipt",
    "PaymentSimulationError",
    "X402RealPaymentError",
]
